### ISSUE TITLE
Question about how to use Find All Tiles and Tile Heatmap

### ISSUE THREAD

**Issue by katubug** [eishiya/tiled-scripts#2]
Hello! Firstly, thank you for your incredibly helpful plugins! I have been using them since yesterday and they have already saved me a ton of hassle!

I want to use the two plugins in the title, I have them installed in the extensions directory, not in folders. I'm not sure whether they need to be, but I don't see any way to use them in the program. I am completely new to this, so if you could point me in the direction of which menu they're in, I'd be very grateful! Thank you for your time. :)

**Comment by eishiya** [comment]
Glad to hear it :D! None of my scripts need to be in subdirectories or anything like that. In fact, Tiled only checks one subdirectory deep in the extensions folder, so if you have nested subdirectories, that can lead to scripts not getting loaded. I have my Tool scripts in directories just for organisation purposes, so that their icons are with them; they'll work as-is, but if you were to put them in an additional subdirectory, they might not load.

My extensions describe where to find the relevant menu items in the comments at the tops of the scripts. Assuming you're talking about "Find Tiles in Project" and "Tileset Heatmap", those are both in the Tileset menu. This menu is only accessible if you're in the Tileset editor, i.e. have a tileset as your active document.

**Comment by eishiya** [comment]
Since there has been no reply for about two months, I'm going to assume the issue is resolved and that there's nothing I need to do. If you're still having problems getting the scripts to load or finding the actions in the Tileset menu, feel free to reopen the issue.

**Comment by katubug** [comment]
Yes, I'm sorry for not responding. Everything is fine now!

Thank you.
