### ISSUE TITLE
question: Import Metatile Terrains

### ISSUE THREAD

**Issue by ghost** [eishiya/tiled-scripts#5]
Hi

I try to understand this but I can't. 

> Builds Terrain data for a metatileset by using the Terrain data from the source Tileset. Useful for speeding up Terrain creation for metatilesets, as the source tiles are usually fewer in number and easier to label. Only tested with orthographic tiles. 

- What is the script doing? What is a metatileset?
- What exactly does it do with the terrains from a source tileset and what's the goal of the script?
- Can you give a small example of a source tileset and the result of this script applied to it?

**Comment by eishiya** [comment]
If you don't understand what a script does, there's a good chance it's not relevant to your needs. Most of these scripts handle niche needs, and I don't expect them to be useful or even understandable to people who aren't facing the exact problems a given script is designed to remedy xP

Metatilesets in Tiled are Tilesets where the source image(s) is/are TileMaps rather than regular images; the tiles are made up of other tiles. Most commonly, and for this script's purpose, they are "Based on Tileset Image" tilesets where the metatileset's tile size is some integer multiple of the TileMap's tile size, e.g. each metatile is 2x2 subtiles.

Since the metatiles are made up of tiles, and those sub-tiles may have Terrain data, it is occasionally useful to build the metatileset's Terrains out of the subtiles' Terrains. This script facilitates that by sampling the Terrains at the corners of the subtiles and building Mixed Terrains for the metatiles using that data.

The most common use case for this script is probably in combination with a script that expands RPG Maker Autotile-style tilesets. RPG Maker autotile tilesets cannot be used directly in Tiled because RPG Maker actually disassembles them into subtiles and them reassembles them into various shapes, but the artwork *can* be used in Tiled if the RPG Maker tileset is broken down into the subtiles and then a new tileset is made with all the different arrangements - a perfect usecase for Metatilesets.
Here is an example of part of an RPG Maker Autotile-style tileset broken up into subtiles with some potential Terrains - not really useable in Tiled directly because Tiled would randomise these tiles incorrectly:
![image](https://github.com/user-attachments/assets/cdb8a20a-999a-4224-b467-70b5969b5a34)
And here are those same sub-tiles rearranged into a blob tileset where each tile is made up of 2x2 of the sub-tiles from the original tileset, useable in Tiled as a Mixed Terrain, with the terrains created by the Import Metatile Terrains script:
![image](https://github.com/user-attachments/assets/89b9335f-6886-4227-97d3-9906ff0882d0)
