### ISSUE TITLE
question: Tileset Heatmap

### ISSUE THREAD

**Issue by ghost** [eishiya/tiled-scripts#6]
I try to understand why it's important to know some tiles are not used so much or are used a lot.
Why should we care about this? Why does this matter to build a tilemap?

> Generates a heatmap of your tileset, making it easy to find over- and under-used tiles.

**Comment by eishiya** [comment]
Just because there's a script for it doesn't mean it's "important" :]

Removing or replacing unused tiles can reduce memory usage. While the memory usage of textures in a tile-based 2D game isn't likely to pose a big issue in a game for modern PCs, it's still a good idea to keep it in check, and it can be a real problem on constrained hardware, such as retro consoles and mobile devices.

Other than that, the frequency of tiles can be useful information, but what it means and whether it's useful depends on the user. For example, if a group of tiles are meant to be randomised but a specific one is used much more often than the others, that can indicate an issue with the randomisation (perhaps the user forgot to randomise, or their Automapping rules aren't working as expected). Seeing under-used tiles highlighted can also serve as a good reminder to make more use of them - maybe there are some neat props in a tileset that the user keeps forgetting to use. Or, maybe those tiles are actually useless, and could use tweaking or replacement to be more useful.
